name: Deploy Release

on:
  release:
    types: 
    - created 

jobs:
  buildAndDeploy:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-18.04
          - macos-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-go@v1
      with:
        go-version: '1.12.x'
    - run: |
        apt-get update -y; apt-get install libgit2-dev cmake libssl-dev -y;
        make build
    - name: Push Binaries
      uses: skx/github-action-publish-binaries@master
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
          args: 'build/mbt*'
