name: Deploy Release

on:
  release:
    types: 
    - created 

jobs:
  buildAndDeploy:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: 
          - ubuntu-18.04
          - macos-latest
        include:
          - os: ubuntu-18.04
            artifact_name: mbt_linux_x86_64
          - os: macos-latest
            artifact_name: mbt_darwin_x86_64
    steps:
    - uses: actions/checkout@master
      with:
        path: ./src

    - uses: actions/setup-go@v1
      with:
        go-version: '1.12.x'

    - name: Install pkg-config
      run: |
        if [ "$RUNNER_OS" == "macOS" ]; then
          brew install pkg-config
        fi

    - name: Build MBT
      env:
        GOPATH: ${{ github.workspace }}/..
        GOBIN: ${{ github.workspace }}/../bin
      run: |
        # Get the release version
        export VERSION=$(jq --raw-output '.release.id' "$GITHUB_EVENT_PATH") 
        make build;

    - name: Push Binaries
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        chmod +x ./scripts/*
        ./scripts/upload_git.sh build/${{ matrix.artifact_name }}
